type MapPatternProps = {
  className?: string;
};

/** Stylized city blocks + roads. Reads as a map at low opacity. */
export function MapPattern({ className }: MapPatternProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 1200 800"
      preserveAspectRatio="xMidYMid slice"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
    >
      <rect
        x="80"
        y="60"
        width="140"
        height="90"
        rx="6"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.5"
      />
      <rect
        x="260"
        y="100"
        width="110"
        height="70"
        rx="6"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.35"
      />
      <rect
        x="420"
        y="50"
        width="180"
        height="120"
        rx="8"
        className="text-orange"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.35"
      />
      <rect
        x="640"
        y="80"
        width="130"
        height="95"
        rx="6"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.45"
      />
      <rect
        x="820"
        y="40"
        width="160"
        height="110"
        rx="8"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.35"
      />
      <rect
        x="1000"
        y="90"
        width="120"
        height="80"
        rx="6"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.3"
      />
      <rect
        x="120"
        y="220"
        width="200"
        height="140"
        rx="8"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.4"
      />
      <rect
        x="360"
        y="260"
        width="150"
        height="100"
        rx="6"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.35"
      />
      <rect
        x="560"
        y="200"
        width="220"
        height="160"
        rx="10"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.5"
      />
      <rect
        x="820"
        y="240"
        width="170"
        height="120"
        rx="8"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.4"
      />
      <rect
        x="60"
        y="420"
        width="180"
        height="130"
        rx="8"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.35"
      />
      <rect
        x="280"
        y="400"
        width="240"
        height="150"
        rx="10"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.45"
      />
      <rect
        x="560"
        y="400"
        width="160"
        height="110"
        rx="6"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.3"
      />
      <rect
        x="760"
        y="380"
        width="200"
        height="140"
        rx="8"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.4"
      />
      <rect
        x="1000"
        y="420"
        width="140"
        height="100"
        rx="6"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.35"
      />
      <rect
        x="200"
        y="580"
        width="190"
        height="120"
        rx="8"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.4"
      />
      <rect
        x="440"
        y="560"
        width="280"
        height="150"
        rx="10"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.45"
      />
      <rect
        x="760"
        y="560"
        width="180"
        height="130"
        rx="8"
        stroke="currentColor"
        strokeWidth="0.75"
        strokeOpacity="0.35"
      />
      <path
        d="M0 200 H1200"
        stroke="currentColor"
        strokeWidth="1.25"
        strokeOpacity="0.6"
      />
      <path
        d="M0 380 H1200"
        stroke="currentColor"
        strokeWidth="1"
        strokeOpacity="0.45"
      />
      <path
        d="M0 540 H1200"
        stroke="currentColor"
        strokeWidth="1.25"
        strokeOpacity="0.5"
      />
      <path
        d="M200 0 V800"
        stroke="currentColor"
        strokeWidth="1"
        strokeOpacity="0.4"
      />
      <path
        d="M480 0 V800"
        stroke="currentColor"
        strokeWidth="1.25"
        strokeOpacity="0.55"
      />
      <path
        d="M720 0 V800"
        stroke="currentColor"
        strokeWidth="1"
        strokeOpacity="0.4"
      />
      <path
        d="M960 0 V800"
        stroke="currentColor"
        strokeWidth="1"
        strokeOpacity="0.35"
      />
      <path
        d="M0 320 Q300 280 600 340 T1200 300"
        stroke="#60a5fa"
        strokeWidth="1"
        strokeOpacity="0.35"
      />
      <path
        d="M0 620 Q400 580 800 640 T1200 600"
        stroke="#60a5fa"
        strokeWidth="0.75"
        strokeOpacity="0.25"
        strokeDasharray="6 10"
      />
      <ellipse
        cx="900"
        cy="180"
        rx="55"
        ry="40"
        stroke="#60a5fa"
        strokeWidth="0.75"
        strokeOpacity="0.3"
      />
      <ellipse
        cx="180"
        cy="520"
        rx="70"
        ry="50"
        stroke="#60a5fa"
        strokeWidth="0.75"
        strokeOpacity="0.25"
      />
      <circle
        cx="480"
        cy="340"
        r="28"
        stroke="currentColor"
        strokeWidth="0.5"
        strokeOpacity="0.35"
      />
      <circle
        cx="480"
        cy="340"
        r="48"
        stroke="currentColor"
        strokeWidth="0.5"
        strokeOpacity="0.15"
      />
    </svg>
  );
}

export function MapGrid({ className }: { className?: string }) {
  return (
    <div
      className={className}
      style={{
        backgroundImage: `
          linear-gradient(rgba(96, 165, 250, 0.5) 1px, transparent 1px),
          linear-gradient(90deg, rgba(96, 165, 250, 0.5) 1px, transparent 1px)
        `,
        backgroundSize: "48px 48px",
      }}
    />
  );
}
